services:
  ecommerce-admin:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ecommerce-admin-app
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/ecommerce-admin/node_modules
      - /app/ecommerce-admin/.next
    command: pnpm --filter ecommerce-admin run dev

  ecommerce-customer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ecommerce-customer-app
    ports:
      - "3001:3001"
    env_file:
      - ./.env.local
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/ecommerce-customer/node_modules
      - /app/ecommerce-customer/.next
    command: pnpm --filter ecommerce-customer run dev
