services:
  ecommerce-admin:
    build:
      context: .                           # Looks at workspace root
      dockerfile: Dockerfile.dev
    container_name: ecommerce-admin
    command: pnpm --filter ecommerce-admin run dev
    ports:
      - "3000:3000"                       # Admin Port
    env_file:
      - ./.env.local                      # Reference path at root
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/ecommerce-admin/node_modules
      - /app/ecommerce-admin/.next

  ecommerce-customer:
    build:
      context: .                           # Looks at workspace root
      dockerfile: Dockerfile.dev
    container_name: ecommerce-customer
    command: pnpm --filter ecommerce-customer run dev
    ports:
      - "3001:3001"                       # Customer Port
    env_file:
      - ./.env.local                      # Reference path at root
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/ecommerce-customer/node_modules
      - /app/ecommerce-customer/.next
